version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 20
  reviewers:
  - caiocampos
  assignees:
  - caiocampos
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 20
  reviewers:
  - caiocampos
  assignees:
  - caiocampos
